init:
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - set PATH=%PATH%;C:\MinGW\bin;%GOPATH%\bin
  - go version
  - go env

# clones and cd's to path
clone_folder: C:\GOPATH\src\github.com\gohugoio\hugo

install:
  - gem install asciidoctor
  - pip install docutils

build_script:
  - make hugo-race check
  - hugo -s docs/
  - hugo --renderToMemory -s docs/
