language: go
sudo: required
dist: precise
go:
  - 1.8.4
  - 1.9.1
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - go get github.com/magefile/mage
  - mage vendor
script:
  - mage hugoRace
  - mage -v check
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
before_install:
  # gem install must be run with sudo on OSX
  - sudo gem install asciidoctor | gem install asciidoctor
