language: go
sudo: false
dist: trusty
git:
  depth: false
go:
  - 1.9.5
  - "1.10.1"
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - go get github.com/magefile/mage
  - mage -v vendor
script:
  - mage -v hugoRace
  - mage -v check
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
before_install:
  - gem install asciidoctor
  - type asciidoctor
